### ISSUE TITLE
🪲[Bug]: Override of PowerShellVersion is not taken into account

### ISSUE THREAD

**Issue by webalexeu** [PSModule/Process-PSModule#49]
### Describe the bug

The module build is not using the overrided (5.1) PowerShellVersion but is setting the default 7.4

### Version information

v3

### To reproduce

Define PowerShellVersion in manifest.psd1

### Code snippet

```powershell
@{
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'
}
```

### Relevant output

```Shell
Link of the Action:
https://github.com/webalexeu/PSWinBGP/actions/runs/11684684422
```

**Comment by MariusStorhaug** [comment]
This should now be all good. [Evidence](https://github.com/PSModule/Process-PSModule/actions/runs/11703204483/job/32593220069?pr=48#step:5:243)
Keeping the issue open until you report back (no longer than a week).

**Comment by webalexeu** [comment]
> This should now be all good. [Evidence](https://github.com/PSModule/Process-PSModule/actions/runs/11703204483/job/32593220069?pr=48#step:5:243) Keeping the issue open until you report back (no longer than a week).

I confirm, thank you very much for your quick hekp
